version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: hoopstore-mysql
    restart: always
    environment:
      MYSQL_DATABASE: hoopstore_db
      MYSQL_USER: hoopstore
      MYSQL_PASSWORD: nbasecretpassword
      MYSQL_ROOT_PASSWORD: nbasecretpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pnbasecretpassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hoopstore-backend
    restart: always
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/hoopstore_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_DRIVER: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_USERNAME: hoopstore
      SPRING_DATASOURCE_PASSWORD: nbasecretpassword
      SPRING_JPA_DIALECT: org.hibernate.dialect.MySQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      APP_JWT_SECRET: KeySuperSeguraYExtensaDeAlMenos64CaracteresParaCumplirConHmacSha2024!
      PORT: 8080
    ports:
      - "8080:8080"

volumes:
  mysql_data:
